@startuml Use Case
skinparam packageStyle rectangle

actor User

rectangle "config file" {
    (Modify) as ModifyConfig
    (Read) as ReadConfig
}

rectangle application {
    (Launch app) as LaunchApp
    (Play sound) as PlaySound
    (Close app) as CloseApp
}

usecase HitDrum as "Hit drum
---
(drumkit, key press, GUI click)"

User -- LaunchApp
User --> ModifyConfig
User -- HitDrum
User --> CloseApp

LaunchApp --> ReadConfig : Parse config
HitDrum --> PlaySound
@enduml